### ISSUE TITLE
slideUp() doesn't work on TR

### ISSUE THREAD

**Issue by razvanphp** [dimmitri/yii2-expand-row-column#2]
Hello,

Thanks for this awesome plugin, really appreciated.

It seems on Chrome (Mac) the slideUp does not work, it just hangs for half a second, then it disappears at once. Would it be possible to fix it somehow or even better, remove the effect completely or make it configurable?

Reference: https://stackoverflow.com/questions/6600021/jquery-slide-up-table-row

**Comment by dimmitri** [comment]
Hello.
I'll try to add an effect selection setting among the three options (fadeIn/fadeOut, slideUp/slideDown, show/hide).

**Comment by razvanphp** [comment]
Works like a charm, thank you!
